# Generated by Django 4.2.11 on 2024-05-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0003_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
